server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: http://localhost:${server.port}/signin
            user-name-attribute: email

okta:
  oauth2:
    redirect-uri: /authorization-code/callback
    issuer: https://<< your okta domain>>/oauth2/default
    clientSecret: << your client secret >>
    clientId: << your client id >>
    scopes:
      - openid
      - email
      - profile
